import '@radix-ui/themes/styles.css';
import './globals.css';

import type { Metadata } from 'next';

import { Theme } from '@radix-ui/themes';

import { Quicksand } from 'next/font/google';

import QueryProvider from '@/provider/QueryProvider';

import TopBar from '@/components/organisms/topbar.organism';

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${quicksand.variable} antialiased`}>
        <QueryProvider>
          <Theme>
            <TopBar />
            {children}
          </Theme>
        </QueryProvider>
      </body>
    </html>
  );
}
